### PR TITLE
Add logo with name png file

### PR DESCRIPTION
**Pull request by GarethCabournDavies**
Note that this logo-with-name is not particularly high quality, and should be replaced at some point with a better version of the name

### CODE REVIEW

**Comment by ahnitz** [comment]
@GarethDaviesGW Do you also have an SVG version of the file available? We should try to make sure that there are vector versions of everything in addition to any "baked" ones.

**Comment by GarethCabournDavies** [comment]
Added - I didn't have an SVG version as I'd made it using GIMP, but converted it, hopefully it is okay as-is

**Comment by GarethCabournDavies** [comment]
Okay the svg I had before was using the pixel graphics as a basis so wasn't really vector at all.
The one now in is fully vector

**Review by ahnitz — APPROVED** [review]

**Comment by GarethCabournDavies** [comment]
For info: I don't have the option of merging on this repo

**Pull request merged**
